# Generated by Django 4.2.3 on 2023-08-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="country",
            field=models.CharField(default=None, max_length=25),
        ),
    ]
