# Generated by Django 4.2.3 on 2023-08-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_record_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="country",
            field=models.CharField(max_length=25),
        ),
    ]
