# Generated by Django 4.2.3 on 2023-08-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_usergroup_alter_record_creator_delete_usergroups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup",
            name="records",
            field=models.ManyToManyField(
                null=True, related_name="group_records", to="website.record"
            ),
        ),
    ]
